import { Tauri } from "next/font/google";
import "./globals.css";
import Header from "./Components/Header";

const inter = Tauri({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <h1>Footer</h1>
      </body>
    </html>
  );
}